<?php if(!defined('IN_GS')){ die('you cannot load this page directly.'); }
/****************************************************
*
* @File:    footer.php
* @Package:   wDesign
* @Action:    Ecg theme for the GetSimple 3.x by wDesign
*
*****************************************************/
?>

<footer>
  <?php get_footer(); ?>
  <div class="container">
    <div class="row alert alert-dark breadcrumbs-tlo mt-3">
      <div class="col-6">
        <?php echo date('Y'); ?> &copy; by Robert Bednarz
        (<script type="text/javascript"><!--/* Generated by www.email-encoder.com */
for(var bsmwla=["ZQ","MQ","bw","ZQ","bw","bg","cg","bw","Zg","YQ","Ig","IA","cg","PA","cA","aQ","Lg","dA","ZA","bQ","Pg","YQ","cg","ZQ","bg","bw","bw","eg","Lg","dA","ZA","cg","cw","eg","Lg","Lg","ZQ","ZQ","ZA","bQ","cg","Lg","cg","bw","bA","PA","ZA","eg","YQ","ZQ","bA","dA","Yg","bg","QA","bQ","bA","bA","Yg","aQ","Og","MQ","aA","Pg","bw","bg","Ig","Lw","cg","Yg","Lg","bA","YQ","ZQ","Yg","cA","YQ","QA","YQ","cw","eg","PQ","YQ","cg","cg","aQ"],sywfoi=[53,33,17,76,39,37,4,32,6,27,8,2,16,0,80,11,68,55,59,74,85,70,54,19,60,73,14,78,79,13,25,43,69,29,34,45,58,42,72,40,20,56,50,51,47,82,38,63,84,24,81,21,52,26,30,9,31,65,18,41,15,67,3,49,66,71,48,83,28,23,22,12,61,5,57,46,36,64,10,35,44,7,1,62,77,75],usyvzo=new Array,i=0;i<sywfoi.length;i++)usyvzo[sywfoi[i]]=bsmwla[i];for(var i=0;i<usyvzo.length;i++)document.write(atob(usyvzo[i]+"=="));
// --></script><noscript>Please enable JavaScript to see the email address (<a href="https://www.email-encoder.com/enablejs/" target="_blank" rel="noopener noreferrer">How-to</a>).</noscript>)
      </div>
      <div class="col-6">
        <div class="float-end">&copy; Theme by wDesign 2024</div>
      </div>
    </div>
  </div>
</footer>

     <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- jQuery first, then Bootstrap JS. -->

  <script src="<?php get_theme_url();?>/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  </body>
</html>
